# Generated by Django 4.1.3 on 2022-12-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0009_remove_offer_category_remove_offer_product"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="offers.offer",
            ),
        ),
    ]
