# Generated by Django 4.1.3 on 2022-12-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
