# Generated by Django 4.1.3 on 2022-12-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_discount_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="discount_price",),
        migrations.RemoveField(model_name="product", name="offer",),
    ]
