# Generated by Django 4.1.3 on 2022-12-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_discount_price_remove_product_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
