# Generated by Django 4.1.3 on 2022-12-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
