# Generated by Django 4.1.3 on 2022-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_offer_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
