# Generated by Django 4.1.3 on 2022-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
