# Generated by Django 4.1.3 on 2022-12-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_useraddress_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraddress", name="profile_picture",),
        migrations.AddField(
            model_name="account",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="userprofile"),
        ),
    ]
