# Generated by Django 4.1.3 on 2022-12-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_useraddress_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
