# Generated by Django 4.1.3 on 2022-12-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_account_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="address_line_1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="city",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="phone_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="useraddress", name="pincode", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="state",
            field=models.CharField(max_length=20),
        ),
    ]
