# Generated by Django 4.1.3 on 2022-12-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_slug"),
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="category",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
    ]
