# Generated by Django 4.1.3 on 2022-12-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
        ("offers", "0002_alter_offer_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
    ]
