# Generated by Django 4.1.3 on 2022-12-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
        ("category", "0002_alter_category_slug"),
        ("offers", "0003_alter_offer_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="category",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
    ]
