# Generated by Django 4.1.3 on 2022-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0006_categoryoffer_delete_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryoffer",
            name="offer_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
