# Generated by Django 4.1.3 on 2022-12-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_slug"),
        ("store", "0002_variation"),
        ("offers", "0007_categoryoffer_offer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_name", models.CharField(blank=True, max_length=50)),
                ("offer_rate", models.IntegerField()),
                ("is_valid", models.BooleanField(default=False)),
                (
                    "category",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="CategoryOffer",),
    ]
