# Generated by Django 4.1.3 on 2022-12-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0008_offer_delete_categoryoffer"),
    ]

    operations = [
        migrations.RemoveField(model_name="offer", name="category",),
        migrations.RemoveField(model_name="offer", name="product",),
    ]
