# Generated by Django 4.1.3 on 2022-12-20 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_discount_price_remove_product_offer"),
        ("offers", "0009_remove_offer_category_remove_offer_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
    ]
