# Generated by Django 4.1.3 on 2022-12-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_discount_price"),
        ("offers", "0010_offer_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
    ]
