# Generated by Django 4.1.3 on 2022-12-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_offer_rate"),
        ("offers", "0011_alter_offer_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="product",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
    ]
