# Generated by Django 4.1.3 on 2022-12-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0012_alter_offer_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="offer", name="is_valid",),
    ]
