# Generated by Django 4.1.3 on 2022-12-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0016_coupon_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
