# Generated by Django 4.1.3 on 2022-12-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0018_alter_coupon_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="offer_description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="offer_image",
            field=models.ImageField(null=True, upload_to="offerimages"),
        ),
    ]
