# Generated by Django 4.1.3 on 2023-01-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0019_offer_offer_description_offer_offer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
