# Generated by Django 4.1.3 on 2023-01-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0020_coupon_is_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="coupon_code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon", name="coupon_discount", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_name",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon", name="minimum_amount", field=models.IntegerField(),
        ),
    ]
