# Generated by Django 4.1.3 on 2023-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0022_usedcoupons"),
    ]

    operations = [
        migrations.RemoveField(model_name="usedcoupons", name="user",),
        migrations.AddField(
            model_name="usedcoupons",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
