# Generated by Django 4.1.3 on 2022-12-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name="payment",
            name="order_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
