# Generated by Django 4.1.3 on 2022-12-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
        ("orders", "0002_payment_order_id_payment_order_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="color",),
        migrations.RemoveField(model_name="orderproduct", name="ram",),
        migrations.RemoveField(model_name="orderproduct", name="variation",),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
