# Generated by Django 4.1.3 on 2022-12-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderproduct_color_remove_orderproduct_ram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
