# Generated by Django 4.1.3 on 2022-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product_price",
            field=models.IntegerField(),
        ),
    ]
